spring:
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848 # 指定 Nacos 服务器的物理地址（IP 和端口）。微服务启动时，就会向这个地址发起连接。(服务注册中心与配置中心的地址)
      username: nacos
      password: nacos
      discovery:      #向 Nacos 注册自己的地址信息，并能从 Nacos 获取其他服务的地址信息
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0 #命名空间（Namespace）ID。(Nacos 租户隔离的核心)
        group: DEFAULT_GROUP #服务分组 (同一个命名空间下，还可以通过不同的 Group 进一步隔离服务）
        ip: 192.168.150.101 #显式指定当前微服务向 Nacos 注册时所声明的自身 IP。
  config:   #微服务从 Nacos 注册中心拉取了 tj-user.yaml 和一系列 shared-*.yaml 文件，并将它们的配置项合并导入到了 Spring 的运行环境中。
    import:
      - nacos:${spring.application.name}.yaml # 去 Nacos 配置中心动态拉取一个和当前服务同名的配置文件(tj-user.yaml)
      - nacos:shared-spring.yaml # 共享spring配置
      - nacos:shared-redis.yaml # 共享redis配置
      - nacos:shared-mybatis.yaml # 共享mybatis配置
      - nacos:shared-logs.yaml # 共享日志配置
      - nacos:shared-feign.yaml # 共享feign配置
logging:
  level:
    com.tianji: debug
